ilham
WebDevRun/cloneivi pull request #9
Opened 2023-04-15 09:58 UTC by Ilhamz10

Добавил кнопки которые есть в footer, добавил глобальные стили в src для обнуления, также создал сторибук для кнопок в footer

2023-04-15 10:23 UTC, Gabageba requested changes

2023-04-15 10:23 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +import cl from './FooterButton.module.scss';
Измени название переменной с cl на styles, чтобы импорты стилей в проекте были в одном стиле

2023-04-15 10:34 UTC, injashkin approved these changes

2023-04-15 11:59 UTC, Gabageba requested changes

2023-04-15 11:59 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +    const { miniInfo, text, children, type } = props
вот тут можно деструктуризировать пропсы сразу в аргументах и не писать 14 строчку. Вот так:
const FooterButton: FC<IProps> = ({ miniInfo, text, children, type }) => {

2023-04-15 11:59 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.stories.tsx
> +import '../../index.scss'
Глобальные стили лучше применять в корневом файле, а не в компоненте

2023-04-15 12:17 UTC, WebDevRun approved these changes

2023-04-15 18:43 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.module.scss
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
font-family можно убрать, он в глобальных стилях

2023-04-15 18:43 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.module.scss
> +.btnContent div{
ой забыл про это
ща исправлю

2023-04-15 18:44 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +    const { subText, text, type, iconSrc, iconAlt } = props
вот тут опять же лучше деструктуризировать сразу
export const FooterButton: FC<IProps> = ({ subText, text, type, iconSrc, iconAlt }) => {

2023-04-15 18:44 UTC, Ilhamz10 commented on src/index.scss
По моему уже Александр сделал, да?

2023-04-15 18:45 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
> +    const { subText, text, type, iconSrc, iconAlt } = props
Да забыл

2023-04-15 18:45 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.module.scss
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
Окей

2023-04-15 18:46 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +                    <div style={subText ? { top: '4px' } : {}}>
тут можно сделать subText && { top: '4px' }, но я так вроде тоже правильно

2023-04-15 18:46 UTC, WebDevRun commented on src/pages/index.tsx
компонент FooterButton убели и импорты для него

2023-04-15 18:46 UTC, WebDevRun commented on src/ui/FooterButton/FooterButton.tsx
Старайся тип any избегать.

2023-04-15 18:49 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
> +                    <div style={subText ? { top: '4px' } : {}}>
Просто подумал вдруг если пустой объект не дать то ошибку покажет

2023-04-15 18:49 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +    children?: any;
children как ReactNode тип

2023-04-15 18:49 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +    iconAlt?: any;
src и alt string вроде как

2023-04-15 18:50 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
Да обычно не использую но в iconSrc он ругался на undefined потому что писал iconSrc?: и он выдал что нельзя undefined и т.д

2023-04-15 18:50 UTC, Ilhamz10 commented on src/pages/index.tsx
окей

2023-04-15 18:50 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
> +    children?: any;
ой забыл children убрать

2023-04-15 18:51 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
можно поставить ! чтобы указать тайпскрипту что ты уверен в том что переменная будет не undefined

2023-04-15 18:51 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
> +    iconAlt?: any;
Они undefined дают из за iconSrc?: из за вопросительного знака поэтому

2023-04-15 18:51 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
Но лучше сделать проверку и он не будет ругаться

2023-04-15 18:52 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
а, или дефолтные значения задать

2023-04-15 18:55 UTC, WebDevRun commented on src/ui/FooterButton/FooterButton.tsx
рендери Image только если есть src и alt

2023-04-15 19:02 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
Все сделал

2023-04-15 19:05 UTC, Gabageba commented on src/ui/FooterButton/FooterButton.tsx
> +                {iconSrc &&
сделай проверку и на iconSrc и на iconAlt

2023-04-16 08:45 UTC, Gabageba approved these changes

2023-04-16 09:32 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
Окей, сделаю, только щас у меня урок будет, закончу его и сделаю

2023-04-16 09:57 UTC, WebDevRun commented on src/ui/FooterButton/FooterButton.stories.tsx
> +    component: FooterButton,
tags: ['autodocs'] добавь

2023-04-17 06:21 UTC, WebDevRun commented on src/ui/FooterButton/FooterButton.tsx
Вообще предлагаю переименовать весь компонент в FooterLink

2023-04-17 11:36 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.tsx
Понял принял

2023-04-17 11:37 UTC, Ilhamz10 commented on src/ui/FooterButton/FooterButton.stories.tsx
> +    component: FooterButton,
Только это не понял, просто после component запятую ставить и туда писать?

2023-04-17 12:28 UTC, WebDevRun commented on src/ui/FooterButton/FooterButton.stories.tsx
> +    component: FooterButton,
ниже строкой вставь. Это авто документирование. Запустишь сторибук поймешь думаю.

2023-04-17 14:17 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +import Image, { ImageProps, StaticImageData } from "next/image";
Неиспользуемые импорты. Те что в скобках

2023-04-17 14:18 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +        styles[type]
Для них стилей нету в scss файле

2023-04-17 14:19 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +                    <div className={styles.buttonText} style={subText ? { top: '4px' } : {}}>
стиля styles.buttonText в scss файле нету.

2023-04-17 14:21 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.stories.tsx
Сделай еще один пример с текстом и сабтекстом, но без иконки

```tsx
export const withoutIcon: Story ={
  args: {
    его стили
  }
}
```

2023-04-17 14:23 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +interface IProps {
FooterLinkProps переименуй

2023-04-17 14:28 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +                        <p className={styles.subText}>{subText}</p>
абсолютное позиционирование убери в стилях. А здесь рендери его по условию: если есть subTest. И вынеси его выше дива. Сам div в p сделай.

2023-04-17 14:30 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +                    <div className={styles.buttonText} style={subText ? { top: '4px' } : {}}>
Здесь style убели и в scss margin-bottom: 4px сделай для subText.

2023-04-17 14:31 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.module.scss
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
есть глобальный font-family. Можно убрать.

2023-04-17 14:33 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.module.scss
> +    text-decoration: none;
Это есть в глобальных стилях. Можно убрать

2023-04-17 14:36 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.tsx
> +export const FooterLink: FC<IProps> = ({ subText, text, type, iconSrc = '', iconAlt = '', href }) => {
Здесь по-моему не надо пустые строки по умолчанию ставить

2023-04-17 15:01 UTC, Ilhamz10 commented on src/ui/FooterLink/FooterLink.module.scss
> +    text-decoration: none;
Хорошо

2023-04-17 15:01 UTC, Ilhamz10 commented on src/ui/FooterLink/FooterLink.module.scss
> +    font-family: Verdana, Geneva, Tahoma, sans-serif;
Хорошо

2023-04-17 15:01 UTC, Ilhamz10 commented on src/ui/FooterLink/FooterLink.tsx
> +                        <p className={styles.subText}>{subText}</p>
Попробую. Подумал через absolute лучше будет

2023-04-17 15:02 UTC, Ilhamz10 commented on src/ui/FooterLink/FooterLink.tsx
> +interface IProps {
Хорошо

2023-04-17 15:02 UTC, Ilhamz10 commented on src/ui/FooterLink/FooterLink.stories.tsx
Хорошо

2023-04-18 04:12 UTC, WebDevRun commented on src/ui/FooterLink/FooterLink.module.scss
Добавь эффект hover на линк

2023-04-18 11:47 UTC, Gabageba approved these changes

2023-04-18 14:21 UTC, WebDevRun approved these changes

2023-04-18 14:26 UTC, injashkin approved these changes

2023-04-18 14:26 UTC, merged